name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Install all dependencies
        run: yarn --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  lint:
    needs: install-dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Run lint
        run: yarn lint

      - name: Run formatter check
        run: yarn format

  build:
    needs: install-dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Build the project
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build/

      - name: Run tests
        run: yarn test:e2e
