name: Release

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.9.3
          cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Install all dependencies
        run: yarn --immutable-cache

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  lint-build-test:
    needs: install-dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.9.3
          cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Run lint
        run: yarn lint

      - name: Run formatter check
        run: yarn format

      - name: Run dead code check
        run: yarn knip --production

      - name: Build binary
        run: yarn build:binary

      - name: Build the project
        run: yarn build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

      - name: Run tests with Docker
        run: yarn test:docker

  release:
    name: Release
    needs: [lint-build-test]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.9.3
          cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: "yarn"

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
